FROM maven:3.8.5-openjdk-11 AS build

WORKDIR /demo1

COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim
  
WORKDIR /demo1

COPY --from=build demo/target/*.jar demo1.jar

EXPOSE 8080
  
ENTRYPOINT ["java", "-jar", "app.jar"]
